services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-dev-app
    container_name: leads-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: leads-db
      DB_USERNAME: leads-user
      DB_PASSWORD: secret

  db:
    image: mysql:8.0
    container_name: leads-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leads-db
      MYSQL_USER: leads-user
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db-data:
